// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsQuotedPrintable.Tests")>]
[<assembly: AssemblyProductAttribute("FsQuotedPrintable")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-03-02T00:00:00.0000000-08:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8116eccf6e443974ef14b848d72c70ec74f14c1b")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsQuotedPrintable.Tests"
    let [<Literal>] AssemblyProduct = "FsQuotedPrintable"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-03-02T00:00:00.0000000-08:00"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
    let [<Literal>] AssemblyInformationalVersion = "0.1.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8116eccf6e443974ef14b848d72c70ec74f14c1b"
