// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsQuotedPrintable.Tests")>]
[<assembly: AssemblyProductAttribute("FsQuotedPrintable")>]
[<assembly: AssemblyVersionAttribute("0.2.4")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-24T00:00:00.0000000-07:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.4")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.4")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","53e90ed5568cbc91515426267d9c48fd98b3a629")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsQuotedPrintable.Tests"
    let [<Literal>] AssemblyProduct = "FsQuotedPrintable"
    let [<Literal>] AssemblyVersion = "0.2.4"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-24T00:00:00.0000000-07:00"
    let [<Literal>] AssemblyFileVersion = "0.2.4"
    let [<Literal>] AssemblyInformationalVersion = "0.2.4"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "53e90ed5568cbc91515426267d9c48fd98b3a629"
